1º EXERCICIO
A EQUIPE DE MARKETING PRECISA FAZER UMA PESQUISA SOBRE NOMES MAIS COMUNS DE SEUS CLIENTES, E PRECISA NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESTÃO CADASTRADOS NO SISTEMA.
Como resolução do desafio:

SELECT firstName,lastName
FROM person.Person;