DESAFIO 1
A EQUIPE DE PRODUÇÃO DE PRODUTOS DE TODAS AS PEÇAS QUE PESAM MAIS QUE 500KG MAS NÃO MAIS QUE 700KG
SELECT Weight
FROM production.Product
WHERE weight > 500 and weight < 700

DESAFIO 2
FOI PEDIDO PELO MARKETING UMA RELAÇÃO DE TODOS OS EMPREGADOS QUE SÃO CASADOS, SOLTEIROS E ASSALARIADOS.
SELECT *
FROM   HumanResources.Employee
WHERE MaritalStatus = 'm' and SalariedFlag = 1

DESAFIO 3 
ACHAR O EMAIL DE UM CARA CHAMADO PETER KREBS:
SELECT *
FROM person.Person
WHERE FirstName = 'peter' and lastName = 'krebs'

SELECT *
FROM person.EmailAddress
WHERE BusinessEntityID = 26