OPERADOR SUM
SERVE PARA SOMAR, SINTAXE EX:
SELECT TOP 10 SUM(linetotal)
FROM Sales.SalesOrderDetail

PRIMEIRO VOCE SELECIONA A TABELA QUE DESEJA SOMAR, APÓS ISSO A COLUNA.

PARA COLOCAR UM NOME PARA A TABELA, USAMOS A SINTAXE AS, EX:
AS "Soma"

OPERADOR MIN:
A FUNÇÃO MIN, É USADA PARA ACHARMOS O MENOR VALOR DA TABELA EX:
SELECT TOP 10 MIN(linetotal)
FROM Sales.SalesOrderDetail

COM ESSA FUNÇÃO, SERÁ RETORNADO O VALOR MINIMO DO TOP 10

A FUNÇÃO MAX, É BASICAMENTE O MESMO, MAS AO INVÉS DO MIN RETORNARÁ O MAX.
SELECT TOP 10 MAX(linetotal)
FROM Sales.SalesOrderDetail

PARA FAZER A MÉDIA USAMOS O AVG

QUE TAMBÉM POSSUI A MESMA SINTAXE, E RETORNARÁ A MÉDIA DO TOP 10
SELECT TOP 10 AVG(linetotal)
FROM Sales.SalesOrderDetail