OPERADOR LIKE
O LIKE SERVE PARA QUANDO VOCE POR EXEMPLO LEMBRAR APENAS UM POUCO DO NOME DA PESSOA EX, OVI...ALGUMA COISA SERIA ASSIM:
SELECT *
FROM person.Person
WHERE FirstName like 'ovi%'

CASO QUERIA SABER SE O NOME TERMINA COM OVI OU TERMINO COM TO OU QUALQUER TERMINAÇÃO SERIA:
SELECT *
FROM person.Person
WHERE FirstName like '%to'

A GENTE INVERTE O LOCAL DO FINAL DO NOME

CASO QUEIRA SABER NO MEIO, EX VANESSA SERIA O ESSA USAMOS
SELECT *
FROM person.Person
WHERE FirstName like '%essa%'
