DESAFIO 1
QUANTAS PESSOAS TEM O MESMO MiddleName AGRUPADAS POR MIDDLENAME
SELECT MiddleName,COUNT(MiddleName)
FROM Person.Person
GROUP BY MiddleName

DESAFIO 2
QUAL A QUANTIDADE QUE CADA PRODUTO É VENDIDO NA LOJA?

SELECT ProductID,AVG(OrderQty)
FROM Sales.SalesOrderDetail
GROUP BY ProductID

DESAFIO 3
QUAIS FORAM AS 10 VENDAS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA POR PRODUTO DO MAIOR PARA O MENOR:
SELECT TOP 10 productid,SUM(LineTotal)
FROM Sales.SalesOrderDetail
GROUP BY productid
ORDER BY SUM(linetotal) DESC

DESAFIO 4
PRECISO SABER QUANTOS PRODUTOS, QUAL E QUANTIDADE MEDIA DE PRODUTOS TEMOS CADASTRADOS NA NOSSAS ODERNS DE SERVIÇOS
SELECT productid,COUNT(productid)
AVG(orderqty) as "media"
FROM Production.WorkOrder
GROUP BY ProductID