DESAFIO FUNDAMENTOS SQL

DESAFIO 1
QUANTOS PRODUTOS TEMOS CADASTRADOS QUE CUSTAM MAIS QUE 1500 DOLARES?
SELECT COUNT(listprice)
FROM Production.Product
WHERE ListPrice > 1500

DESAFIO 2
QUANTAS PESSOAS TEMOS COM O SOBRENOME Q INICIA COM A LETRA P
SELECT COUNT(lastname)
FROM Person.Person
WHERE LastName LIKE 'p%'

DESAFIO 3
EM QUANTAS CIDADES UNICAS ESTÃO CADASTRADOS NOSSOS CLIENTES?
SELECT COUNT (DISTINCT(city))
FROM Person.Address


DESAFIO 4 
QUAIS SÃO AS CIDADES UNICAS CADASTRADAS NO NOSSO SISTEMA?
SELECT DISTINCT(city)
FROM Person.Address

DESAFIO 5 
QUANTOS PRODUTOS VERMELHOS TEM O PREÇO ENTRE 500 A 1000 DOLARES?
SELECT COUNT(*)
FROM Production.Product
WHERE color = 'red'
AND ListPrice between 500 and 1000

DESAFIO 6
QUANTOS PRODUTOS CADASTRADOS TEM A PALAVRA ROAD NO NOME DELES?
SELECT COUNT (*)
FROM Production.Product
WHERE Name LIKE '%road%'