DESAFIO 1
ESTAMOS QUERENDO IDENTIFICAR AS PROVINCIAS COM MAIOR NUMERO DE CADASTROS NO NOSSO SISTEMA, ENTÃO É PRECISO ENCONTRAR QUAIS PROVINCIAS ESTÃO REGISTRADAS NO BANCO DE DADOS MAIS QUE 1000X.

SELECT stateprovinceid,COUNT(stateprovinceid)
FROM Person.Address
GROUP BY StateProvinceID
HAVING COUNT(stateprovinceid) > 1000


DESAFIO 2
OS GERENTES QUEREM SABER QUAIS PRODUTOS NÃO ESTÃO TRAZENDO EM MÉDIA NO MIN 1M EM TOTAL DE VENDAS

SELECT productid,AVG(linetotal)
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(linetotal) < 1000000