DESAFIO 1 
QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS
SELECT COUNT(*)
FROM production.Product

DESAFIO 2 
QUANTOS TAMANHOS UNICOS TEMOS CADASTRADOS EM NOSSA TABELA?
SELECT COUNT(size)
FROM production.Product