OPERADOR IN
USAMOS O IN JUNTO AO WHERE EX:
VALOR IN (VALOR1, VALOR2)
COLOR IN ('BLUE', 'RED')

SELECT *
FROM Person.Person
WHERE BusinessEntityID IN (2,7,13)

TAMBEM PODENDO UTILIZAR O NOT, QUE RETORNARIA TODOS OS ENTITYID MENOS OS QUE VOCE COLOCAR COMO PARAMETRO SEIRA:
SELECT *
FROM Person.Person
WHERE BusinessEntityID NOT IN (2,7,13)
